dataset_path: "data/val_data.pkl"
model_path: "models/pixelcnn/pixelcnn_final.pt"
results_path: "results/pixelcnn/"
model_params:
  dim: 256
  n_layers: 15
vqvae: 
  model_path: "models/vqvae_baseline/vqvae_baseline.pt"
  model_params:
    input_channels: 3
    output_channels: 3
    num_hiddens: 128
    num_residual_layers: 3
    num_residual_hiddens: 64
    codebook_size: 512
    codebook_embed_dim: 5
    commitment_cost: 0.25
    recon_weight: 1.0         # no modifs
    entropy_weight: 0.0       # not from the paper
    decay: 0.0
    imsize: 48
    ignore_background: False  # For dot/color datasets
batch_size: 32
num_epochs: 300
patience: 5
lr: 3e-4
weight_decay: 1e-5